#!/usr/bin/env bash

CRAPPER_APPRISE_CONF=${CRAPPER_APPRISE_CONF:-}
CRAPPER_FILTER=${CRAPPER_FILTER:-Finished}
CRAPPER_SERVICES=${CRAPPER_SERVICES:-}
CRAPPER_TAG=${CRAPPER_TAG:-crop}

if [[ -f /opt/crop/crapper.env ]]; then
    source /opt/crop/crapper.env
fi

if [[ -z "$(command -v apprise)" ]]; then
    sudo pip install apprise
fi


if [[ -n "${CRAPPER_SERVICES:-}" ]]; then
    if [[ -f /etc/systemd/system/crop_clean.service ]]; then
        sudo sed -i -E 's/^ExecStart=/opt/crop/crop clean$/ExecStart=/opt/crop/crapper clean/g' /etc/systemd/system/crop_clean.service
    fi
    if [[ -f /etc/systemd/system/crop_sync.service ]]; then
        sudo sed -i -E 's/^ExecStart=/opt/crop/crop sync$/ExecStart=/opt/crop/crapper sync/g' /etc/systemd/system/crop_sync.service
    fi
    if [[ -f /etc/systemd/system/crop_upload.service ]]; then
        sudo sed -i -E 's/^ExecStart=/opt/crop/crop upload$/ExecStart=/opt/crop/crapper upload/g' /etc/systemd/system/crop_upload.service
    fi
fi

/opt/crop/crop "$@" 3>&1 1>&2 2>&3 | tee >(grep -P "${CRAPPER_FILTER}" | apprise --tag="${CRAPPER_TAG}" --config="${CRAPPER_APPRISE_CONF}")
