#!/usr/bin/env bash

CRAPPER_APPRISE_SERVICE=${CRAPPER_APPRISE_SERVICE:-}
CRAPPER_FILTER=${CRAPPER_FILTER:-Finished}
CRAPPER_SERVICES=${CRAPPER_SERVICES:-}

if [[ -f /opt/crop/crapper.env ]]; then
    source /opt/crop/crapper.env
fi

if [[ -z "$(command -v apprise)" ]]; then
    pip install apprise
fi


if [[ -n "${CRAPPER_SERVICES:-}" ]]; then
    if [[ -f /etc/systemd/system/crop_clean.service ]]; then
        sudo sed -i -E 's/^ExecStart=\/opt\/crop\/crop clean$/ExecStart=\/opt\/crop\/crapper clean/g' /etc/systemd/system/crop_clean.service
    fi
    if [[ -f /etc/systemd/system/crop_sync.service ]]; then
        sudo sed -i -E 's/^ExecStart=\/opt\/crop\/crop sync$/ExecStart=\/opt\/crop\/crapper sync/g' /etc/systemd/system/crop_sync.service
    fi
    if [[ -f /etc/systemd/system/crop_upload.service ]]; then
        sudo sed -i -E 's/^ExecStart=\/opt\/crop\/crop upload$/ExecStart=\/opt\/crop\/crapper upload/g' /etc/systemd/system/crop_upload.service
    fi
    sudo systemctl daemon-reload
fi

#/opt/crop/crop "$@" 3>&1 1>&2 2>&3 | tee >(grep -P "${CRAPPER_FILTER}" | apprise -vv "${CRAPPER_APPRISE_SERVICE}")
/opt/crop/crop "$@" 3>&1 1>&2 2>&3 | grep -P "${CRAPPER_FILTER}" | apprise -vv "${CRAPPER_APPRISE_SERVICE}"
