#!/usr/bin/env bash

CRAPPER_FILTER=${CRAPPER_FILTER:-Finished}
CRAPPER_TAG=${CRAPPER_TAG:-crop}

if [[ -f /opt/crop/crapper.env ]]; then
    source /opt/crop/crapper.env
fi

if [[ -z "$(command -v apprise)" ]]; then
    sudo pip install apprise
fi

/opt/crop/crop "$@" 3>&1 1>&2 2>&3 | tee >(grep -P "${CRAPPER_FILTER}" | apprise --tag="${CRAPPER_TAG}")
